baseurl = "https://www.example.com/"
title = "Black & Light"
author = "David Hamp-Gonsalves"
canonifyurls = true
languagecode = "ch"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Black & Light"

[[menu.main]]
    name = "About"
    url  = "/about"
[[menu.main]]
    name = "Friends"
    url  = "https://blog.gemslyho.org/friends/"
[[menu.main]]
    name = "Home"
    url  = "https://www.gemslyho.org"

