baseurl = "https://blog-html.gemslyho.org/"
title = "Gemsly Hoshino"
author = "Gemsly Hoshino"
canonifyurls = true
languagecode = "zh-cn"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

disableKinds = ["taxonomy", "term"]

[params]
    sitename = "Gemsly Hoshino"
    description = "一个纯净、无广告、零追踪的独立技术博客。"
    disableWebFonts = true

[[menu.main]]
    name = "About"
    url  = "/about"
[[menu.main]]
    name = "Friends"
    url  = "https://blog.gemslyho.org/friends/"
[[menu.main]]
    name = "Home"
    url  = "https://www.gemslyho.org"

