baseurl = "http://blog-html.gemslyho.org/"
title = "Gemsly Hoshino"
author = "Gemsly Hoshino"
canonifyurls = true
languagecode = "zh-cn"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

disableKinds = ["taxonomy", "term"]

[params]
    sitename = "Gemsly Hoshino"
    description = "一个纯净、无广告、向下兼容的独立技术博客。"
    disableWebFonts = true

[[menu.main]]
    name = "About"
    url  = "/about"
[[menu.main]]
    name = "Privacy Policy"
    url  = "/privacy"
[[menu.main]]
    name = "RSS"
    url  = "/index.xml"
[[menu.main]]
    name = "Sitemap"
    url  = "/sitemap.xml"
